<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="/buttons.css">
    <title>CSGODatabase Viewer</title>
</head>

<body>
    <div class="container">
        <h1 class="top">Cases</h1>
        <div class="center list">

            <a href="/cases/dreams_nightmares_case" class="btn-hover fill color-1">Dreams & Nightmares Case</a>
            <a href="/cases/operation_riptide_case" class="btn-hover fill color-2">Operation Riptide Case</a>
            <a href="/cases/snakebite_case" class="btn-hover fill color-3">Snakebite Case</a>
            <a href="/cases/operation_broken_fang_case" class="btn-hover fill color-4">Operation Broken Fang Case</a>

            <a href="/cases/fracture_case" class="btn-hover fill color-5">Fracture Case</a>
            <a href="/cases/prisma_2_case" class="btn-hover fill color-6">Prisma 2 Case</a>
            <a href="/cases/shattered_web_case" class="btn-hover fill color-7">Shattered Web Case</a>
            <a href="/cases/cs20_case" class="btn-hover fill color-8">CS20 Case</a>
            <a href="/cases/prisma_case" class="btn-hover fill color-8">Prisma Case</a>
            <a href="/cases/danger_zone_case" class="btn-hover fill color-10">Danger Zone Case</a>
            <a href="/cases/horizon_case" class="btn-hover fill color-11">Horizon Case</a>
            <a href="/cases/clutch_case" class="btn-hover fill color-1">Clutch Case</a>
            <a href="/cases/spectrum_2_case" class="btn-hover fill color-2">Spectrum 2 Case</a>
            <a href="/cases/operation_hydra_case" class="btn-hover fill color-3">Operation Hydra Case</a>
            <a href="/cases/spectrum_case" class="btn-hover fill color-4">Spectrum Case</a>
            <a href="/cases/glove_case" class="btn-hover fill color-5">Glove Case</a>
            <a href="/cases/gamma_2_case" class="btn-hover fill color-6">Gamma 2 Case</a>
            <a href="/cases/gamma_case" class="btn-hover fill color-7">Gamma Case</a>
            <a href="/cases/chroma_3_case" class="btn-hover fill color-8">Chroma 3 Case</a>
            <a href="/cases/operation_wildfire_case" class="btn-hover fill color-9">Operation Wildfire Case</a>
            <a href="/cases/revolver_case" class="btn-hover fill color-10">Revolver Case</a>
            <a href="/cases/shadow_case" class="btn-hover fill color-11">Shadow Case</a>
            <a href="/cases/falchion_case" class="btn-hover fill color-1">Falchion Case</a>
            <a href="/cases/chroma_2_case" class="btn-hover fill color-2">Chroma 2 Case</a>
            <a href="/cases/chroma_case" class="btn-hover fill color-3">Chroma Case</a>
            <a href="/cases/operation_vanguard_weapon_case" class="btn-hover fill color-4">Operation Vanguard Weapon
                Case</a>
            <a href="/cases/esports_2014_summer_case" class="btn-hover fill color-5">eSports 2014 Summer Case</a>
            <a href="/cases/operation_breakout_weapon_case" class="btn-hover fill color-6">Operation Breakout Weapon
                Case</a>
            <a href="/cases/huntsman_weapon_case" class="btn-hover fill color-7">Huntsman Weapon Case</a>
            <a href="/cases/operation_phoenix_weapon_case" class="btn-hover fill color-8">Operation Phoenix Weapon
                Case</a>
            <a href="/cases/csgo_weapon_case_3" class="btn-hover fill color-9">CS:GO Weapon Case 3</a>
            <a href="/cases/esports_2013_winter_case" class="btn-hover fill color-10">eSports 2013 Winter Case</a>
            <a href="/cases/winter_offensive_weapon_case" class="btn-hover fill color-11">Winter Offensive Weapon Case</a>

            <a href="/cases/csgo_weapon_case_2" class="btn-hover fill color-1">CS:GO Weapon Case 2</a>
            <a href="/cases/operation_bravo_case" class="btn-hover fill color-2">Operation Bravo Case</a>
            <a href="/cases/esports_2013_case" class="btn-hover fill color-3">eSports 2013 Case</a>
            <a href="/cases/csgo_weapon_case" class="btn-hover fill color-4">CS:GO Weapon Case</a>

        </div>
    </div>
</body>

</html>