<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="/buttons.css">
    <title>CSGODatabase Viewer</title>
</head>

<body>
    <div class="container">
        <h1 class="top">Collections</h1>
        <div class="center list">
            <a href="/collections/train_collection" class="btn-hover fill color-1">2021 Train Collection</a>
            <a href="/collections/norse_collection" class="btn-hover fill color-2">The Norse Collection</a>
            <a href="/collections/2021_vertigo_collection" class="btn-hover fill color-3">2021 Vertigo Collection</a>
            <a href="/collections/St_marc_collection" class="btn-hover fill color-4">The St. Marc Collection</a>
            <a href="/collections/ancient_collection" class="btn-hover fill color-5">The Ancient Collection</a>
            <a href="/collections/cache_collection" class="btn-hover fill color-6">The Cache Collection</a>
            <a href="/collections/control_collection" class="btn-hover fill color-7">The Control Collection</a>
            <a href="/collections/chop_shop_collection" class="btn-hover fill color-8">The Chop Shop Collection</a>
            <a href="/collections/havoc_collection" class="btn-hover fill color-9">The Havoc Collection</a>
            <a href="/collections/cobblestone_collection" class="btn-hover fill color-10">The Cobblestone Collection</a>
            <a href="/collections/canals_collection" class="btn-hover fill color-11">The Canals Collection</a>
            <a href="/collections/gods_and_monsters_collection" class="btn-hover fill color-1">The Gods and Monsters
                Collection</a>
            <a href="/collections/overpass_collection" class="btn-hover fill color-2">The Overpass Collection</a>
            <a href="/collections/2021_dust_2_collection" class="btn-hover fill color-3">2021 Dust 2 Collection</a>
            <a href="/collections/rising_sun_collection" class="btn-hover fill color-4">The Rising Sun Collection</a>
            <a href="/collections/2021_mirage_collection" class="btn-hover fill color-5">2021 Mirage Collection</a>
            <a href="/collections/2018_inferno_collection" class="btn-hover fill color-6">The 2018 Inferno
                Collection</a>

            <a href="/collections/2018_nuke_collection" class="btn-hover fill color-7">The 2018 Nuke Collection</a>
            <a href="/collections/bank_collection" class="btn-hover fill color-8">The Bank Collection</a>
            <a href="/collections/italy_collection" class="btn-hover fill color-9">The Italy Collection</a>
            <a href="/collections/dust_2_collection" class="btn-hover fill color-10">The Dust 2 Collection</a>
            <a href="/collections/lake_collection" class="btn-hover fill color-11">The Lake Collection</a>
            <a href="/collections/safehouse_collection" class="btn-hover fill color-1">The Safehouse Collection</a>
            <a href="/collections/train_collection" class="btn-hover fill color-2">The Train Collection</a>
            <a href="/collections/inferno_collection" class="btn-hover fill color-3">The Inferno Collection</a>
            <a href="/collections/assault_collection" class="btn-hover fill color-4">The Assault Collection</a>
            <a href="/collections/aztec_collection" class="btn-hover fill color-5">The Aztec Collection</a>
            <a href="/collections/baggage_collection" class="btn-hover fill color-6">The Baggage Collection</a>
            <a href="/collections/mirage_collection" class="btn-hover fill color-7">The Mirage Collection</a>
            <a href="/collections/canals_collection" class="btn-hover fill color-8">The Canals Collection</a>
            <a href="/collections/nuke_collection" class="btn-hover fill color-9">The Nuke Collection</a>
            <a href="/collections/vertigo_collection" class="btn-hover fill color-10">The Vertigo Collection</a>
            <a href="/collections/office_collection" class="btn-hover fill color-11">The Office Collection</a>
            <a href="/collections/dust_collection" class="btn-hover fill color-1">The Dust Collection</a>
            <a href="/collections/militia_collection" class="btn-hover fill color-2">The Militia Collection</a>
        </div>
    </div>
    </div>
</body>

</html>