<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="/buttons.css">
    <title>CSGODatabase Viewer</title>
</head>

<body>
    <div class="container">
        <div class="center grid">
            <h1 class="heading">CSGO Database Viewer</h1>
            <div class="buttons">
                <a href="/collections" class="btn-hover with-radius color-2">Collections</a>
            </div>
            <div class="buttons">
                <a href="/cases" class="btn-hover with-radius color-3">Cases</a>
            </div>
        </div>
    </div>
    </div>
</body>

</html>